name: Test CI

on: [push, pull_request]

jobs:
  test-flake:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main

      - name: Cache Nix store
        uses: DeterminateSystems/magic-nix-cache-action@main

      - name: Check up flake configuration
        run: nix flake check --all-systems --show-trace

  # build-arm64:
  #   strategy:
  #     fail-fast: false
  #     matrix:
  #       instance: [ 1, 2 ]

  #   runs-on: ubuntu-latest-arm

  #   steps:
  #     - name: Check out the repository
  #       uses: actions/checkout@v4

  #     - name: Install Nix
  #       uses: DeterminateSystems/nix-installer-action@main

  #     - name: Cache Nix store
  #       uses: DeterminateSystems/magic-nix-cache-action@main

  #     - name: Build NixOS configuration
  #       run: nix build .#nixosConfigurations.Kolyma-${{ matrix.instance }}.config.system.build.toplevel --show-trace
